apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: modeler-ojt
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: "gcr.io/accu-platform/modeler-ojt-backend:tag5"
          ports:
            - containerPort: 8080
